% Create array of file paths/names for your masks %
% This script will unify masks, so put the paths in for the masks you want
% unified. For example, if you want a bilateral striatal mask, put in the
% two files for R and L striatum.

filenames = {'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=10.677_extent=18357_roi=Location not in atlas_peak=[16_4_-12].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=3.333_extent=18357_roi=Occipital_Inf_L_peak=[-46_-76_-6].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=3.457_extent=2179_roi=Temporal_Inf_R_peak=[52_-54_-14].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=4.382_extent=174_roi=Precentral_L_peak=[-20_-20_70].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=4.393_extent=257_roi=Frontal_Inf_Tri_L_peak=[-40_36_14].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=4.636_extent=601_roi=Occipital_Inf_R_peak=[30_-92_-8].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=4.884_extent=147_roi=SupraMarginal_L_peak=[-48_-32_34].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=4.964_extent=492_roi=Location not in atlas_peak=[22_-26_60].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=5.107_extent=672_roi=Frontal_Mid_2_L_peak=[-24_28_56].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=5.116_extent=455_roi=Frontal_Sup_2_R_peak=[26_46_44].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=5.198_extent=441_roi=Thalamus_R_peak=[12_-16_16].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=5.443_extent=549_roi=Location not in atlas_peak=[-18_-12_16].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=5.580_extent=147_roi=Cerebelum_6_R_peak=[18_-72_-26].nii', ...
'masks/glm2_wins_adversarial - losses_adversarial_cluster_t=6.451_extent=2179_roi=Fusiform_R_peak=[38_-40_-26].nii'};

unify_masks(filenames, 'masks/glm2_con7.nii');
view_mask('masks/glm2_con7.nii');