
 [allSubjects, subjdirs, goodRuns, goodSubjs, subj_original_indices] = optCon_getSubjectsDirsAndRuns();

%ccnl_fmri_con(exploration_expt(), 1, ...
%    {'RS + SR - RR - SS', 'RR - SS', 'RS - SR', 'RS', 'SR', 'RR', 'SS', 'choice_onset', 'feedback_onset'}, ...
%     subjs);
% 
% ccnl_fmri_con(optCon_expt(), 1, ...
%    {'benevolent', 'adversarial', 'benevolent - adversarial'}, ...
%     goodSubjs);


% old version
% ccnl_fmri_con(optCon_expt(), 2, ...
%    {'wins_benevolent - losses_benevolent', 'wins_adversarial - losses_adversarial', ...
%     'wins_benevolent + wins_adversarial - losses_benevolent - losses_adversarial', ... %all wins minus all losses
%     'wins_benevolent - losses_benevolent - wins_adversarial + losses_adversarial'}, ... 
%     goodSubjs);
% 
% ccnl_fmri_con(optCon_expt(), 2, ...
%    {'wins_benevolent - losses_benevolent', 'wins_adversarial - losses_adversarial', ...
%     'wins_benevolent + wins_adversarial - losses_benevolent - losses_adversarial', ... %all wins minus all losses
%     'wins_benevolent - losses_benevolent - wins_adversarial + losses_adversarial', ...
%     'wins_adversarial - losses_adversarial - wins_benevolent + losses_benevolent', ...
%     'wins_adversarial - wins_benevolent', ...
%     'losses_adversarial - losses_benevolent'}, ... 
%     goodSubjs);
%         
% % 
% ccnl_fmri_con(optCon_expt(), 3, ...
%    {'benevolent', 'adversarial', 'benevolent - adversarial'}, ...
%     goodSubjs);
% 
% ccnl_fmri_con(optCon_expt(), 4, ...
%    {'RPEpsi'}, ...
%     goodSubjs);
% 
% ccnl_fmri_con(optCon_expt(), 5, ...
%    {'RPE', 'psi', 'psi - RPE', 'RPE - psi'}, ...
%     goodSubjs);
% 
% ccnl_fmri_con(optCon_expt(), 6, ...
%    {'RPE'}, ...
%     goodSubjs);

